<a href="https://colab.research.google.com/github/Yuxi-Cn/Dashboard-Design/blob/main/8_27_update.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Library Importation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
# access the csv file in my google drive
from google.colab import drive
drive.mount('/content/drive')
# link to the folder of Colab Notebooks
%cd '/content/drive/MyDrive/ColabNotebooks/AcademicProjectsDU/Research_Electricity-GB'

Mounted at /content/drive
/content/drive/MyDrive/ColabNotebooks/AcademicProjectsDU/Research_Electricity-GB

In [ ]:
# read csv file
csv_fuel = 'df_fuel_gb.csv'
df1 = pd.read_csv(csv_fuel)

# filter rows based on the specified condition (the data is only prior to 2023-01-01)
filtered_df = df1[df1['DATETIME'] < '2024-01-01 00:00:00+00']

# save the filtered data to a new CSV file
filtered_df.to_csv('09-24_fuel_gb.csv', index=False)

df = pd.read_csv('09-24_fuel_gb.csv') # read the new data
pd.set_option('display.max_columns', None) # show all columns
df.head(5) # show the first five rows of data

,DATETIME,GAS,COAL,NUCLEAR,WIND,HYDRO,IMPORTS,BIOMASS,OTHER,SOLAR,STORAGE,GENERATION,CARBON_INTENSITY,LOW_CARBON,ZERO_CARBON,RENEWABLE,FOSSIL,GAS_perc,COAL_perc,NUCLEAR_perc,WIND_perc,HYDRO_perc,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
0,2009-01-01 00:00:00+00,8351,15035,7098,276,246,2517,0,0,0,0,33523,525,7620,7620,522,23386,24.9,44.8,21.2,0.8,0.7,7.5,0.0,0.0,0.0,0.0,100,22.7,22.7,1.6,69.8
1,2009-01-01 00:30:00+00,8473,15093,7087,255,245,2498,0,0,0,0,33651,526,7587,7587,500,23566,25.2,44.9,21.1,0.8,0.7,7.4,0.0,0.0,0.0,0.0,100,22.5,22.5,1.5,70.0
2,2009-01-01 01:00:00+00,8435,15082,7073,229,246,2464,0,0,0,0,33529,527,7549,7549,475,23517,25.2,45.0,21.1,0.7,0.7,7.3,0.0,0.0,0.0,0.0,100,22.5,22.5,1.4,70.1
3,2009-01-01 01:30:00+00,8289,15020,7064,213,246,2430,0,0,0,0,33261,528,7522,7522,459,23309,24.9,45.2,21.2,0.6,0.7,7.3,0.0,0.0,0.0,0.0,100,22.6,22.6,1.4,70.1
4,2009-01-01 02:00:00+00,8258,14984,7051,196,246,2361,0,0,0,0,33096,529,7493,7493,442,23242,25.0,45.3,21.3,0.6,0.7,7.1,0.0,0.0,0.0,0.0,100,22.6,22.6,1.3,70.2

In [ ]:
df.tail()

,DATETIME,GAS,COAL,NUCLEAR,WIND,HYDRO,IMPORTS,BIOMASS,OTHER,SOLAR,STORAGE,GENERATION,CARBON_INTENSITY,LOW_CARBON,ZERO_CARBON,RENEWABLE,FOSSIL,GAS_perc,COAL_perc,NUCLEAR_perc,WIND_perc,HYDRO_perc,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
262939,2023-12-31 21:30:00+00,2943,230,4670,12263,672,5208,981,259,0,0,27226,66,18586,17605,12935,3173,10.8,0.8,17.2,45.0,2.5,19.1,3.6,1.0,0.0,0.0,100,68.3,64.7,47.5,11.7
262940,2023-12-31 22:00:00+00,2874,229,4672,11639,661,5080,983,221,0,0,26359,67,17955,16972,12300,3103,10.9,0.9,17.7,44.2,2.5,19.3,3.7,0.8,0.0,0.0,100,68.1,64.4,46.7,11.8
262941,2023-12-31 22:30:00+00,2898,229,4670,12258,553,3826,987,245,0,0,25666,68,18468,17481,12811,3127,11.3,0.9,18.2,47.8,2.2,14.9,3.8,1.0,0.0,0.0,100,72.0,68.1,49.9,12.2
262942,2023-12-31 23:00:00+00,2870,229,4674,12741,543,3709,982,235,0,0,25983,66,18940,17958,13284,3099,11.0,0.9,18.0,49.0,2.1,14.3,3.8,0.9,0.0,0.0,100,72.9,69.1,51.1,11.9
262943,2023-12-31 23:30:00+00,2856,230,4673,13169,535,3606,986,280,0,0,26335,67,19363,18377,13704,3086,10.8,0.9,17.7,50.0,2.0,13.7,3.7,1.1,0.0,0.0,100,73.5,69.8,52.0,11.7

In [ ]:
# check if there are any missing data
missing_data = df.isnull().sum()
print(missing_data)

DATETIME            0
GAS                 0
COAL                0
NUCLEAR             0
WIND                0
HYDRO               0
IMPORTS             0
BIOMASS             0
OTHER               0
SOLAR               0
STORAGE             0
GENERATION          0
CARBON_INTENSITY    0
LOW_CARBON          0
ZERO_CARBON         0
RENEWABLE           0
FOSSIL              0
GAS_perc            0
COAL_perc           0
NUCLEAR_perc        0
WIND_perc           0
HYDRO_perc          0
IMPORTS_perc        0
BIOMASS_perc        0
OTHER_perc          0
SOLAR_perc          0
STORAGE_perc        0
GENERATION_perc     0
LOW_CARBON_perc     0
ZERO_CARBON_perc    0
RENEWABLE_perc      0
FOSSIL_perc         0
dtype: int64

In [ ]:
# show dataset information
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262944 entries, 0 to 262943
Data columns (total 32 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATETIME          262944 non-null  object
 1   GAS               262944 non-null  int64
 2   COAL              262944 non-null  int64
 3   NUCLEAR           262944 non-null  int64
 4   WIND              262944 non-null  int64
 5   HYDRO             262944 non-null  int64
 6   IMPORTS           262944 non-null  int64
 7   BIOMASS           262944 non-null  int64
 8   OTHER             262944 non-null  int64
 9   SOLAR             262944 non-null  int64
 10  STORAGE           262944 non-null  int64
 11  GENERATION        262944 non-null  int64
 12  CARBON_INTENSITY  262944 non-null  int64
 13  LOW_CARBON        262944 non-null  int64
 14  ZERO_CARBON       262944 non-null  int64
 15  RENEWABLE         262944 non-null  int64
 16  FOSSIL            262944 non-null  int64
 17  GAS_perc          262944 non-null  float64
 18  COAL_perc         262944 non-null  float64
 19  NUCLEAR_perc      262944 non-null  float64
 20  WIND_perc         262944 non-null  float64
 21  HYDRO_perc        262944 non-null  float64
 22  IMPORTS_perc      262944 non-null  float64
 23  BIOMASS_perc      262944 non-null  float64
 24  OTHER_perc        262944 non-null  float64
 25  SOLAR_perc        262944 non-null  float64
 26  STORAGE_perc      262944 non-null  float64
 27  GENERATION_perc   262944 non-null  int64
 28  LOW_CARBON_perc   262944 non-null  float64
 29  ZERO_CARBON_perc  262944 non-null  float64
 30  RENEWABLE_perc    262944 non-null  float64
 31  FOSSIL_perc       262944 non-null  float64
dtypes: float64(14), int64(17), object(1)
memory usage: 64.2+ MB
None

In [ ]:
# show the shape of dataset
# 245424 data includes all data-records per half hour from 2009-01-01 00:00:00 to 2022-12-31 23:30:00
print(df.shape)

(262944, 32)

1. **Set index**: Set the 'DATETIME' column as the index.

2. **Calculate sum**: Calculate monthly, seasonal, annual sum for each source and carbon intensity.

3. **Decimal Precision**: Set decimal places to 2 for clear and concise data values.

4. **Unit Conversion**: Convert summed source generation from kWh to GW and summed carbon intensity from gCO2/kWh to kgCO2/kWh for enhancing readability.

5. **Calculate individual source percentages**: When summing data, compute source percentages by dividing each source's generation by the total generation, instead of summing up all percentages when operating '.sum()' function. This is to accurately represent their contributions.

In [3]:
df = pd.read_csv('09-24_fuel_gb.csv')

In [4]:
# convert the 'DATETIME' column to datetime
df['DATETIME'] = pd.to_datetime(df['DATETIME'])
# set the 'DATETIME' column as the index
df.set_index('DATETIME', inplace=True)

# resample the data to monthly intervals and sum the values
df_month = df.resample('M').sum()
# resample the data to seasonal intervals (3 months) and sum the values
df_season = df.resample('Q').sum()
# resample the data to annual intervals  and sum the values
df_annual = df.resample('Y').sum()

In [5]:
print(df_annual.info())
print(df_annual.shape)

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 15 entries, 2009-12-31 00:00:00+00:00 to 2023-12-31 00:00:00+00:00
Freq: A-DEC
Data columns (total 31 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAS               15 non-null     int64
 1   COAL              15 non-null     int64
 2   NUCLEAR           15 non-null     int64
 3   WIND              15 non-null     int64
 4   HYDRO             15 non-null     int64
 5   IMPORTS           15 non-null     int64
 6   BIOMASS           15 non-null     int64
 7   OTHER             15 non-null     int64
 8   SOLAR             15 non-null     int64
 9   STORAGE           15 non-null     int64
 10  GENERATION        15 non-null     int64
 11  CARBON_INTENSITY  15 non-null     int64
 12  LOW_CARBON        15 non-null     int64
 13  ZERO_CARBON       15 non-null     int64
 14  RENEWABLE         15 non-null     int64
 15  FOSSIL            15 non-null     int64
 16  GAS_perc          15 non-null     float64
 17  COAL_perc         15 non-null     float64
 18  NUCLEAR_perc      15 non-null     float64
 19  WIND_perc         15 non-null     float64
 20  HYDRO_perc        15 non-null     float64
 21  IMPORTS_perc      15 non-null     float64
 22  BIOMASS_perc      15 non-null     float64
 23  OTHER_perc        15 non-null     float64
 24  SOLAR_perc        15 non-null     float64
 25  STORAGE_perc      15 non-null     float64
 26  GENERATION_perc   15 non-null     int64
 27  LOW_CARBON_perc   15 non-null     float64
 28  ZERO_CARBON_perc  15 non-null     float64
 29  RENEWABLE_perc    15 non-null     float64
 30  FOSSIL_perc       15 non-null     float64
dtypes: float64(14), int64(17)
memory usage: 3.8 KB
None
(15, 31)

In [16]:
df_annual.head()

,GAS,COAL,NUCLEAR,WIND,HYDRO,IMPORTS,BIOMASS,OTHER,SOLAR,STORAGE,GENERATION,CARBON_INTENSITY,LOW_CARBON,ZERO_CARBON,RENEWABLE,FOSSIL,GAS_perc,COAL_perc,NUCLEAR_perc,WIND_perc,HYDRO_perc,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
DATETIME,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2009-12-31 00:00:00+00:00,294815.43,197615.86,130004.16,8314.68,7116.43,13379.30,0.0,0.00,0.0,7233.58,658479.31,7793.81,0.0,145435.22,15431.11,492431.29,44.77,30.01,19.74,1.26,1.08,2.03,0.0,0.00,0.00,1.10,100,0.0,22.09,2.34,74.78
2010-12-31 00:00:00+00:00,314190.82,205681.73,117022.08,9209.66,4276.62,13756.85,0.0,0.00,0.0,6248.26,670386.11,8085.18,0.0,130508.46,13486.34,519872.55,46.87,30.68,17.46,1.37,0.64,2.05,0.0,0.00,0.00,0.93,100,0.0,19.47,2.01,77.55
2011-12-31 00:00:00+00:00,254089.46,206791.42,129542.22,23825.55,7390.41,17211.73,0.0,0.00,0.0,5839.31,644690.10,7878.34,0.0,160758.19,31215.97,460880.88,39.41,32.08,20.09,3.70,1.15,2.67,0.0,0.00,0.00,0.91,100,0.0,24.94,4.84,71.49
2012-12-31 00:00:00+00:00,166160.49,274343.16,132031.58,31082.40,6549.38,27471.47,0.0,4183.34,0.0,5819.37,647641.18,8864.34,0.0,169663.36,37631.79,440503.65,25.66,42.36,20.39,4.80,1.01,4.24,0.0,0.65,0.00,0.90,100,0.0,26.20,5.81,68.02
2013-12-31 00:00:00+00:00,160275.82,251537.10,131896.47,42727.58,5828.79,35158.30,0.0,7704.97,4170.5,5603.99,644903.53,8320.64,0.0,184623.36,52726.87,411812.92,24.85,39.00,20.45,6.63,0.90,5.45,0.0,1.19,0.65,0.87,100,0.0,28.63,8.18,63.86

**Convert Data Units and Decimal Places & Differentiate Zero_carbon and Low_carbon**

In [7]:
# define DataFrames
dfs = [df_month, df_season, df_annual]

# units conversion and precision adjustment
columns_to_convert = ['GAS', 'COAL', 'NUCLEAR', 'WIND', 'HYDRO', 'IMPORTS', 'BIOMASS', 'OTHER', 'SOLAR',
                      'STORAGE', 'GENERATION', 'LOW_CARBON', 'ZERO_CARBON', 'RENEWABLE', 'FOSSIL']

# replace the 'LOW_CARBON' data with the 'BIOMASS' data
# to ensure there is no overlap between each type of generation (such as "ZERO_CARBON" and LOW_CARBON")
for df in dfs:
    df['LOW_CARBON'] = df['BIOMASS']

# convert MWh to GWh
for df in dfs:
    df[columns_to_convert] = df[columns_to_convert] / 1000

# convert g/kWh to kg/kWh for carbon intensity
for df in dfs:
    df['CARBON_INTENSITY'] = df['CARBON_INTENSITY'] / 1000

# calculate percentages for source and generation categories
for df in dfs:
    source_columns = ['GAS', 'COAL', 'NUCLEAR', 'WIND', 'HYDRO', 'IMPORTS', 'BIOMASS', 'OTHER',
                      'SOLAR', 'STORAGE', 'GENERATION', 'LOW_CARBON', 'ZERO_CARBON', 'RENEWABLE', 'FOSSIL']
    for source in source_columns:
        perc_column = source + '_perc'
        df[perc_column] = (df[source] / df['GENERATION']) * 100

# round all columns to 2 decimal places
for df in dfs:
    df[:] = df.round(2)

# set GENERATION_perc to 100 for all years
for df in dfs:
    df['GENERATION_perc'] = 100

**The Unit of Data after the Conversion:**

*   Sources Generation Amount: **GWh**

*   Carbon Intensity: **kgCO2/kWh**

*   Source Percentage: **percent (%)**

**Convert the datetime index to the corresponding level (year, quarter, month)**

In [17]:
# for df_annual (Year)
df_annual.index = df_annual.index.to_period('Y').to_timestamp()

# for df_season (Quarter)
df_season.index = df_season.index.to_period('Q').to_timestamp()

# for df_month (Month)
df_month.index = df_month.index.to_period('M').to_timestamp()

<ipython-input-17-2687e87354e3>:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_annual.index = df_annual.index.to_period('Y').to_timestamp()
<ipython-input-17-2687e87354e3>:5: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_season.index = df_season.index.to_period('Q').to_timestamp()
<ipython-input-17-2687e87354e3>:8: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_month.index = df_month.index.to_period('M').to_timestamp()

In [18]:
# Compare data between the first and last year (based on annual data)
first_year = df_annual.iloc[:1]   # Select the first row
last_year = df_annual.iloc[-1:]   # Select the last row

# Concatenate the selected rows into a single DataFrame
compare_rows = pd.concat([first_year, last_year])

pd.set_option('display.max_columns', None)  # Display all columns

# Compare the two rows to observe differences in generation sources
compare_rows

,GAS,COAL,NUCLEAR,WIND,HYDRO,IMPORTS,BIOMASS,OTHER,SOLAR,STORAGE,GENERATION,CARBON_INTENSITY,LOW_CARBON,ZERO_CARBON,RENEWABLE,FOSSIL,GAS_perc,COAL_perc,NUCLEAR_perc,WIND_perc,HYDRO_perc,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
DATETIME,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2009-01-01,294815.43,197615.86,130004.16,8314.68,7116.43,13379.30,0.00,0.00,0.00,7233.58,658479.31,7793.81,0.00,145435.22,15431.11,492431.29,44.77,30.01,19.74,1.26,1.08,2.03,0.00,0.00,0.00,1.1,100,0.00,22.09,2.34,74.78
2023-01-01,172935.42,5526.75,76595.86,157967.41,6496.11,66856.45,26717.48,5136.33,26639.13,3315.26,548186.25,2610.25,26717.48,267698.51,191102.65,178462.17,31.55,1.01,13.97,28.82,1.19,12.20,4.87,0.94,4.86,0.6,100,4.87,48.83,34.86,32.56

### Data Visualisation

#### Trends: Energy *Evolution*
*Area Chart and Line Chart*

##### **1. Overall Trends**

**Area Chart - All Generation Types**

In [101]:
import plotly.graph_objs as go
import pandas as pd

# Select only the generation-source columns
columns_to_plot = ['GAS', 'COAL', 'NUCLEAR', 'WIND', 'HYDRO', 'IMPORTS',
                   'BIOMASS', 'OTHER', 'SOLAR', 'STORAGE']
df_annual_stack = df_annual[columns_to_plot]

# Create a stacked area chart
fig = go.Figure()

for col in columns_to_plot:
    fig.add_trace(go.Scatter(
        x=df_annual_stack.index, y=df_annual_stack[col],
        mode='lines', stackgroup='one', name=col
    ))

# Highlight the period from 2015 to 2020 with a shaded area
fig.add_shape(type="rect",
              x0="2015-01-01", x1="2020-01-01",
              y0=0, y1=1,
              xref="x", yref="paper",
              fillcolor="LightSalmon", opacity=0.3, layer="below", line_width=0)

# Add annotation with the years highlighted
fig.add_annotation(
    x='2017-01-01', y=0.5,  # Adjust the coordinates as needed
    text="Wind energy overtakes coal\n(2015-2020)",
    showarrow=True,
    arrowhead=2,
    ax=-50,
    ay=-50,
    bgcolor="rgba(255, 255, 255, 0.8)"
)

# Update layout for aesthetics and axis styling
fig.update_layout(
    title='Annual Energy Generation Trends by Source',
    xaxis_title='Year',
    yaxis_title='Energy Generation (GWh)',
    legend_title='Energy Sources',
    template='plotly_white',
    font=dict(size=14),
    legend=dict(x=1.1, y=1.02),
    plot_bgcolor='rgba(0,0,0,0)',  # Transparent background
    xaxis=dict(
        showline=True,
        linewidth=2,
        linecolor='black',  # Bottom border
        mirror=False,       # Disable mirroring
        title_font=dict(size=14, color='black')
    ),
    yaxis=dict(
        showline=True,
        linewidth=2,
        linecolor='black',  # Left border
        mirror=False,       # Disable mirroring
        title_font=dict(size=14, color='black')
    ),
    legend_itemclick="toggleothers",  # Enable the functionality to highlight a single line/area
)

fig.show()

*Note: Click the legend to highlight the area*

**Line Chart - Fossil vs. Renewable Generation**

In [100]:
import plotly.graph_objects as go

# Define fossil fuels and renewables
fossil_fuels = ['GAS', 'COAL', 'NUCLEAR', 'OTHER']
renewables = ['WIND', 'HYDRO', 'BIOMASS', 'SOLAR', 'STORAGE']

# Create a figure for fossil fuels
fig_fossil = go.Figure()

# Plot fossil fuels data
for col in fossil_fuels:
    fig_fossil.add_trace(go.Scatter(x=df_annual.index, y=df_annual[col], mode='lines+markers', name=col))

# Update layout for the fossil fuels chart with legend item click behavior
fig_fossil.update_layout(
    title='Fossil Fuels Generation Trends',
    xaxis_title='Year',
    yaxis_title='Generation (GWh)',
    font=dict(size=14),
    plot_bgcolor='rgba(0,0,0,0)',  # Transparent background
    xaxis=dict(
        showline=True,
        linewidth=2,
        linecolor='black',  # Bottom border
        gridcolor='lightgray',  # Light gray grid
        gridwidth=0.5
    ),
    yaxis=dict(
        showline=True,
        linewidth=2,
        linecolor='black',  # Left border
        gridcolor='lightgray',  # Light gray grid
        gridwidth=0.5
    ),
    legend=dict(
        x=1.05,
        y=1,
        traceorder='normal',
        font=dict(size=12),
    ),
    legend_itemclick="toggleothers",  # Enable the functionality to highlight a single line
)

# Create a figure for renewables
fig_renewable = go.Figure()

# Plot renewables data
for col in renewables:
    fig_renewable.add_trace(go.Scatter(x=df_annual.index, y=df_annual[col], mode='lines+markers', name=col))

# Update layout for the renewables chart with legend item click behavior
fig_renewable.update_layout(
    title='Renewables Generation Trends',
    xaxis_title='Year',
    yaxis_title='Generation (GWh)',
    font=dict(size=14),
    plot_bgcolor='rgba(0,0,0,0)',  # Transparent background
    xaxis=dict(
        showline=True,
        linewidth=2,
        linecolor='black',  # Bottom border
        gridcolor='lightgray',  # Light gray grid
        gridwidth=0.5
    ),
    yaxis=dict(
        showline=True,
        linewidth=2,
        linecolor='black',  # Left border
        gridcolor='lightgray',  # Light gray grid
        gridwidth=0.5
    ),
    legend=dict(
        x=1.05,
        y=1,
        traceorder='normal',
        font=dict(size=12),
    ),
    legend_itemclick="toggleothers",  # Enable the functionality to highlight a single line
)

# Show both charts together
fig_fossil.show()
fig_renewable.show()

*Note: Click the legend to highlight the line*

**Generation catrgories vs. Carbon Intensity**

In [89]:
import plotly.graph_objects as go

# List of columns, only CARBON_INTENSITY has different units
type_columns = ['CARBON_INTENSITY', 'LOW_CARBON', 'ZERO_CARBON', 'RENEWABLE', 'FOSSIL']

# Create the figure
fig = go.Figure()

# Plot data for columns with GWh unit on the left y-axis
for column in type_columns[1:]:
    color = 'orange' if column == 'FOSSIL' else None  # Set fossil line to orange
    fig.add_trace(go.Scatter(
        x=df_annual.index,
        y=df_annual[column],
        mode='lines+markers',
        name=column,
        yaxis='y1',
        line=dict(color=color)
    ))

# Plot 'CARBON_INTENSITY' data on the right y-axis
fig.add_trace(go.Scatter(
    x=df_annual.index,
    y=df_annual['CARBON_INTENSITY'],
    mode='lines+markers',
    name='CARBON_INTENSITY',
    yaxis='y2',
    line=dict(color='violet', dash='dash')
))

# Update layout to include two y-axes, grid, and axis borders
fig.update_layout(
    title='Generation Trends of Energy Types and Carbon Intensity',
    xaxis=dict(
        title='Year',
        showline=True,  # Bottom border
        linewidth=2,
        linecolor='black',
        mirror=False,  # Right border
        gridcolor='lightgray',  # Very light gray grid
        gridwidth=0.5,
        titlefont=dict(size=16, color='black'),  # Ensure title font color matches axis number color
        tickfont=dict(size=14, color='black'),   # Set tick label color
    ),
    yaxis=dict(
        title='Generation (GWh)',
        titlefont=dict(size=16, color='blue'),  # Set the title font color to blue
        tickfont=dict(size=14, color='blue'),  # Set the tick font color to blue
        showline=True,  # Left border
        linewidth=2,
        linecolor='black',
        gridcolor='lightgray',  # Very light gray grid
        gridwidth=0.5,
        mirror=True  # Right border
    ),
    yaxis2=dict(
        title='Carbon Intensity (kgCO2/kWh)',
        titlefont=dict(size=16, color='violet'),  # Set the title font color to violet
        tickfont=dict(size=14, color='violet'),  # Corrected: Set the tick font color to violet
        overlaying='y',
        side='right',
        showline=True,  # Right border for the secondary axis
        linewidth=2,
        linecolor='black'
    ),
    legend=dict(
        x=0.82,  # Adjust as needed for your position
        y=0.99,
        xanchor='left',
        yanchor='top',
        bordercolor="Black",
        borderwidth=1,
        orientation="v"
    ),
    plot_bgcolor='rgba(255, 255, 255, 1)',  # White background for contrast
    margin=dict(t=50, l=50, r=100, b=50),  # Increased right margin to make space for the legend
    legend_itemclick="toggleothers",  # Enable the functionality to highlight a single line
)

# Enhance contrast and readability
fig.update_traces(marker=dict(size=6, line=dict(width=2)),
                  line=dict(width=2))

# Display the plot
fig.show()

*Note: Click the legend to highlight the line*

In [98]:
import plotly.graph_objects as go

# List of columns
type_columns = ['CARBON_INTENSITY', 'RENEWABLE']

# Create the figure
fig = go.Figure()

# Plot the carbon intensity data as lines on the right y-axis
fig.add_trace(go.Scatter(
    x=df_annual.index,
    y=df_annual['CARBON_INTENSITY'],
    mode='lines+markers',
    name='Carbon Intensity',
    yaxis='y2',
    line=dict(color='red', dash='dash'),
    marker=dict(size=6)  # Marker size for the line plot
))

# Plot the renewable data as bars on the left y-axis
fig.add_trace(go.Bar(
    x=df_annual.index,
    y=df_annual['RENEWABLE'],
    name='Renewable',
    yaxis='y1',
    marker_color='green',  # Bar color
    opacity=0.6
))

# Update layout to include two y-axes, grid, and axis borders
fig.update_layout(
    title='Carbon Intensity and Renewable Generation Trends',
    xaxis=dict(
        title='Year',
        showline=True,  # Bottom border
        linewidth=2,
        linecolor='black',
        mirror=False,  # Right border
        gridcolor='lightgray',  # Very light gray grid
        gridwidth=0.5,
        titlefont=dict(size=16, color='black'),  # Ensure title font color matches axis number color
        tickfont=dict(size=14, color='black'),   # Set tick label color
    ),
    yaxis=dict(
        title='Renewable Generation (GWh)',
        titlefont=dict(size=16, color='green'),  # Set the title font color to green
        tickfont=dict(size=14, color='green'),  # Set the tick font color to green
        showline=True,  # Left border
        linewidth=2,
        linecolor='black',
        gridcolor='lightgray',  # Very light gray grid
        gridwidth=0.5,
        mirror=True  # Right border
    ),
    yaxis2=dict(
        title='Carbon Intensity (kgCO2/kWh)',
        titlefont=dict(size=16, color='red'),  # Set the title font color to violet
        tickfont=dict(size=14, color='red'),  # Set the tick font color to violet
        overlaying='y',
        side='right',
        showline=True,  # Right border for the secondary axis
        linewidth=2,
        linecolor='black'
    ),
    legend=dict(
        x=0.75,  # Adjust as needed for your position
        y=0.99,
        xanchor='left',
        yanchor='top',
        bordercolor="Black",
        borderwidth=1,
        orientation="v"
    ),
    plot_bgcolor='rgba(255, 255, 255, 1)',  # White background for contrast
    margin=dict(t=50, l=50, r=100, b=50),  # Increased right margin to make space for the legend
    legend_itemclick="toggleothers",  # Enable the functionality to highlight a single line
)

# Enhance contrast and readability for Scatter traces
fig.update_traces(
    selector=dict(type='scatter'),  # Apply to scatter traces only
    line=dict(width=2)  # Line width for scatter traces
)

# Display the plot
fig.show()

*Note: Click the legend to highlight measures*

##### **2. Quarterly Variations**

In [78]:
import plotly.graph_objects as go
import pandas as pd

# Assume df_season is your DataFrame equivalent to seasonal_sum
# Plot the generation data

fig = go.Figure()

# Add the main generation line plot
fig.add_trace(go.Scatter(
    x=df_season.index,
    y=df_season['GENERATION'],
    mode='lines+markers',
    marker=dict(size=8, symbol='circle', color='blue'),
    line=dict(color='blue', width=2),
    name='Generation',
    hovertemplate='Generation: %{y:.2f} GWh<br>Date: %{x|%Y-%m-%d}<extra></extra>'
))

# Annotate the first and last fourth quarter (2009-10-01 and 2023-10-01)
first_fourth_quarter_index = df_season.index.get_loc(pd.Timestamp('2009-10-01'))
last_fourth_quarter_index = df_season.index.get_loc(pd.Timestamp('2023-10-01'))

fig.add_annotation(
    x=df_season.index[first_fourth_quarter_index],
    y=df_season['GENERATION'].iloc[first_fourth_quarter_index],
    text=f"{df_season['GENERATION'].iloc[first_fourth_quarter_index]:.2f}",
    showarrow=True,
    arrowhead=1,
    ax=0,
    ay=-40,
    font=dict(color='black', size=12)
)

fig.add_annotation(
    x=df_season.index[last_fourth_quarter_index],
    y=df_season['GENERATION'].iloc[last_fourth_quarter_index],
    text=f"{df_season['GENERATION'].iloc[last_fourth_quarter_index]:.2f}",
    showarrow=True,
    arrowhead=1,
    ax=0,
    ay=-40,
    font=dict(color='black', size=12)
)

# Highlight every second and third quarter (specifically, 03-31 to 09-30), including 2023
for year in range(2009, 2024):  # Adjusting for 2023 data
    highlight_color = 'lightblue' if year == 2023 else 'gray'
    opacity_value = 0.7 if year == 2023 else 0.4

    fig.add_vrect(
        x0=pd.Timestamp(f'{year}-03-31'),
        x1=pd.Timestamp(f'{year}-06-30'),
        fillcolor=highlight_color,
        opacity=opacity_value,
        layer='below',
        line_width=0,
    )
    fig.add_vrect(
        x0=pd.Timestamp(f'{year}-06-30'),
        x1=pd.Timestamp(f'{year}-09-30'),
        fillcolor=highlight_color,
        opacity=opacity_value,
        layer='below',
        line_width=0,
    )

# Update layout for better aesthetics and proper x-axis ticks
fig.update_layout(
    title='Seasonal Trends in Total Electricity Generation',
    xaxis=dict(
        title='Year',
        titlefont=dict(size=14),
        tickfont=dict(size=12),
        showline=True,  # Add bottom border
        linewidth=2,
        linecolor='black',
        dtick="M24",  # Set the x-axis to show every 2 years
        tickformat="%Y"  # Format the tick labels to display years
    ),
    yaxis=dict(
        title='Generation Amount (GWh)',
        titlefont=dict(size=14),
        tickfont=dict(size=12),
        showline=True,  # Add left border
        linewidth=2,
        linecolor='black'
    ),
    hovermode="x unified",  # Show all hover info in a unified box
    plot_bgcolor='white',
    margin=dict(t=50, l=50, r=50, b=50),
    showlegend=False
)

# Update x-axis to rotate labels for better readability
fig.update_xaxes(tickangle=45)

# Add a comment comparing the first and last fourth quarter generation difference
first_fourth_quarter = df_season['GENERATION'].loc[pd.Timestamp('2009-10-01')]
last_fourth_quarter = df_season['GENERATION'].loc[pd.Timestamp('2023-10-01')]
generation_diff = last_fourth_quarter - first_fourth_quarter

# Position the generation difference annotation above the last data point annotation
fig.add_annotation(
    x=pd.Timestamp('2023-10-01'),
    y=last_fourth_quarter + 5,  # Slightly above the last data point annotation
    text=f"Generation Difference (2009-2023 Q4): {generation_diff:.2f} GWh",
    showarrow=False,
    font=dict(color='red', size=12),
    bgcolor="white",
    opacity=0.8,
    xanchor='center',
    yanchor='top'
)

# Display the plot
fig.show()

In [59]:
df_season

,GAS,COAL,NUCLEAR,WIND,HYDRO,IMPORTS,BIOMASS,OTHER,SOLAR,STORAGE,GENERATION,CARBON_INTENSITY,LOW_CARBON,ZERO_CARBON,RENEWABLE,FOSSIL,GAS_perc,COAL_perc,NUCLEAR_perc,WIND_perc,HYDRO_perc,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
DATETIME,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2009-01-01,65309.86,76007.42,32144.58,2383.05,2215.84,2741.13,0.00,0.00,0.00,1984.06,182785.89,2270.76,0.00,36743.46,4598.90,141317.27,35.73,41.58,17.59,1.30,1.21,1.50,0.00,0.00,0.00,1.09,100,0.00,20.10,2.52,77.31
2009-04-01,67518.42,38280.78,33763.45,1782.18,1237.70,6076.17,0.00,0.00,0.00,1589.07,150247.74,1788.38,0.00,36783.31,3019.87,105799.21,44.94,25.48,22.47,1.19,0.82,4.04,0.00,0.00,0.00,1.06,100,0.00,24.48,2.01,70.42
2009-07-01,75679.86,31499.90,33259.37,1948.04,1494.90,3242.74,0.00,0.00,0.00,1845.76,148970.54,1714.60,0.00,36702.31,3442.94,107179.76,50.80,21.15,22.33,1.31,1.00,2.18,0.00,0.00,0.00,1.24,100,0.00,24.64,2.31,71.95
2009-10-01,86307.29,51827.76,30836.75,2201.41,2167.99,1319.27,0.00,0.00,0.00,1814.69,176475.14,2020.07,0.00,35206.14,4369.40,138135.06,48.91,29.37,17.47,1.25,1.23,0.75,0.00,0.00,0.00,1.03,100,0.00,19.95,2.48,78.27
2010-01-01,86814.48,62826.44,34150.96,2049.18,999.73,1212.85,0.00,0.00,0.00,1710.56,189764.28,2087.27,0.00,37199.93,3048.96,149640.91,45.75,33.11,18.00,1.08,0.53,0.64,0.00,0.00,0.00,0.90,100,0.00,19.60,1.61,78.86
2010-04-01,80975.23,36836.46,26198.71,1256.41,776.83,4045.94,0.00,0.00,0.00,1509.93,151599.55,1880.18,0.00,28232.00,2033.28,117811.70,53.41,24.30,17.28,0.83,0.51,2.67,0.00,0.00,0.00,1.00,100,0.00,18.62,1.34,77.71
2010-07-01,73527.51,37847.56,24629.01,2441.87,1069.17,5682.82,0.00,0.00,0.00,1407.90,146605.81,1908.42,0.00,28140.06,3511.04,111375.07,50.15,25.82,16.80,1.67,0.73,3.88,0.00,0.00,0.00,0.96,100,0.00,19.19,2.39,75.97
2010-10-01,72873.60,68171.27,32043.40,3462.19,1430.89,2815.25,0.00,0.00,0.00,1619.88,182416.47,2209.30,0.00,36936.48,4893.06,141044.87,39.95,37.37,17.57,1.90,0.78,1.54,0.00,0.00,0.00,0.89,100,0.00,20.25,2.68,77.32
2011-01-01,66155.68,67364.78,36480.95,4369.17,1552.28,3418.77,0.00,0.00,0.00,1548.35,180889.95,2115.88,0.00,42402.40,5921.46,133520.45,36.57,37.24,20.17,2.42,0.86,1.89,0.00,0.00,0.00,0.86,100,0.00,23.44,3.27,73.81
2011-04-01,64237.47,35720.34,35827.80,4620.39,1507.55,4189.11,0.00,0.00,0.00,1295.07,147397.74,1730.51,0.00,41955.76,6127.95,99957.82,43.58,24.23,24.31,3.13,1.02,2.84,0.00,0.00,0.00,0.88,100,0.00,28.46,4.16,67.82
2011-07-01,67512.50,36378.76,29684.60,4951.74,1588.04,5320.20,0.00,0.00,0.00,1413.92,146849.76,1824.34,0.00,36224.38,6539.78,103891.25,45.97,24.77,20.21,3.37,1.08,3.62,0.00,0.00,0.00,0.96,100,0.00,24.67,4.45,70.75
2011-10-01,56183.81,67327.55,27548.87,9884.24,2742.54,4283.65,0.00,0.00,0.00,1581.98,169552.65,2207.61,0.00,40175.64,12626.78,123511.36,33.14,39.71,16.25,5.83,1.62,2.53,0.00,0.00,0.00,0.93,100,0.00,23.70,7.45,72.85
2012-01-01,45629.76,81538.35,32423.05,8155.02,2472.49,6259.99,0.00,583.94,0.00,1576.22,178638.83,2338.80,0.00,43050.56,10627.52,127168.11,25.54,45.64,18.15,4.57,1.38,3.50,0.00,0.33,0.00,0.88,100,0.00,24.10,5.95,71.19
2012-04-01,42310.92,59797.49,34663.48,5867.48,865.12,6569.88,0.00,212.68,0.00,1319.85,151606.89,2129.60,0.00,41396.07,6732.59,102108.41,27.91,39.44,22.86,3.87,0.57,4.33,0.00,0.14,0.00,0.87,100,0.00,27.30,4.44,67.35
2012-07-01,37553.87,54687.78,33749.70,6762.01,1186.08,8741.47,0.00,1078.49,0.00,1372.66,145132.08,2049.04,0.00,41697.80,7948.09,92241.66,25.88,37.68,23.25,4.66,0.82,6.02,0.00,0.74,0.00,0.95,100,0.00,28.73,5.48,63.56
2012-10-01,40665.93,78319.54,31195.34,10297.90,2025.69,5900.13,0.00,2308.22,0.00,1550.64,172263.38,2346.91,0.00,43518.93,12323.58,118985.47,23.61,45.46,18.11,5.98,1.18,3.43,0.00,1.34,0.00,0.90,100,0.00,25.26,7.15,69.07
2013-01-01,45502.30,78525.52,34087.96,11059.45,1498.53,6646.64,0.00,2537.87,448.20,1422.75,181729.22,2235.78,0.00,47094.13,13006.18,124027.82,25.04,43.21,18.76,6.09,0.82,3.66,0.00,1.40,0.25,0.78,100,0.00,25.91,7.16,68.25
2013-04-01,40939.79,55766.78,29100.59,9904.89,1174.89,8670.81,0.00,2733.85,1551.11,1327.68,151170.41,2041.42,0.00,41731.50,12630.90,96706.57,27.08,36.89,19.25,6.55,0.78,5.74,0.00,1.81,1.03,0.88,100,0.00,27.61,8.36,63.97
2013-07-01,35456.82,52630.42,34845.01,6853.49,855.10,10891.99,0.00,839.41,1609.81,1350.37,145332.42,1981.97,0.00,44163.41,9318.39,88087.24,24.40,36.21,23.98,4.72,0.59,7.49,0.00,0.58,1.11,0.93,100,0.00,30.39,6.41,60.61
2013-10-01,38376.90,64614.38,33862.90,14909.75,2300.28,8948.85,0.00,1593.84,561.38,1503.20,166671.48,2061.47,0.00,51634.32,17771.40,102991.28,23.03,38.77,20.32,8.95,1.38,5.37,0.00,0.96,0.34,0.90,100,0.00,30.98,10.66,61.79
2014-01-01,36034.77,65210.96,30796.00,16407.27,3101.62,11442.23,0.00,3198.10,1033.67,1562.27,168786.89,2004.41,0.00,51338.55,20542.56,101245.73,21.35,38.64,18.25,9.72,1.84,6.78,0.00,1.89,0.61,0.93,100,0.00,30.42,12.17,59.98
2014-04-01,41315.45,42199.43,32610.48,7758.02,1426.17,11558.22,0.00,3863.82,2861.57,1279.42,144872.56,1768.43,0.00,44656.23,12045.75,83514.88,28.52,29.13,22.51,5.36,0.98,7.98,0.00,2.67,1.98,0.88,100,0.00,30.82,8.31,57.65
2014-07-01,51656.22,31738.98,29420.27,8752.52,946.80,12008.37,0.00,3745.65,2954.37,1207.02,142430.19,1637.64,0.00,42073.96,12653.69,83395.19,36.27,22.28,20.66,6.15,0.66,8.43,0.00,2.63,2.07,0.85,100,0.00,29.54,8.88,58.55
2014-10-01,44247.75,54211.72,26716.74,17940.76,2374.50,11604.31,0.00,4137.74,1062.50,1551.60,163847.62,1924.52,0.00,48094.51,21377.76,98459.47,27.01,33.09,16.31,10.95,1.45,7.08,0.00,2.53,0.65,0.95,100,0.00,29.35,13.05,60.09
2015-01-01,39232.37,57468.86,33840.94,19204.14,2735.90,11103.82,0.00,4107.71,1950.87,1428.00,171072.59,1822.84,0.00,57731.84,23890.90,96701.22,22.93,33.59,19.78,11.23,1.60,6.49,0.00,2.40,1.14,0.83,100,0.00,33.75,13.97,56.53
2015-04-01,39248.91,33205.82,31635.18,13018.73,1858.94,12257.59,0.00,4243.26,6084.20,1258.31,142810.94,1515.93,0.00,52597.06,20961.87,72454.73,27.48,23.25,22.15,9.12,1.30,8.58,0.00,2.97,4.26,0.88,100,0.00,36.83,14.68,50.73
2015-07-01,45127.68,25265.96,31027.09,11622.37,1244.45,12687.63,0.00,5668.81,5152.93,1245.06,139041.96,1433.84,0.00,49046.84,18019.75,70393.64,32.46,18.17,22.31,8.36,0.90,9.13,0.00,4.08,3.71,0.90,100,0.00,35.27,12.96,50.63
2015-10-01,45008.71,33057.22,34912.08,19513.91,2349.59,10453.22,0.00,8556.91,1547.77,1436.29,156835.70,1480.78,0.00,58323.36,23411.28,78065.93,28.70,21.08,22.26,12.44,1.50,6.67,0.00,5.46,0.99,0.92,100,0.00,37.19,14.93,49.78
2016-01-01,59986.88,27406.74,32333.81,17547.24,2666.23,12959.49,0.00,8639.90,3010.37,1499.98,166050.67,1411.18,0.00,55557.66,23223.84,87393.62,36.13,16.51,19.47,10.57,1.61,7.80,0.00,5.20,1.81,0.90,100,0.00,33.46,13.99,52.63
2016-04-01,61088.73,8101.13,31149.48,11837.97,1054.81,11984.86,0.00,7741.49,7495.76,1320.60,141774.85,1119.81,0.00,51538.02,20388.54,69189.86,43.09,5.71,21.97,8.35,0.74,8.45,0.00,5.46,5.29,0.93,100,0.00,36.35,14.38,48.80
2016-07-01,58121.75,4594.16,35065.39,13181.69,1401.32,9805.12,0.00,4960.74,7107.69,1332.33,135570.16,995.97,0.00,56756.08,21690.70,62715.91,42.87,3.39,25.87,9.72,1.03,7.23,0.00,3.66,5.24,0.98,100,0.00,41.86,16.00,46.26
2016-10-01,75311.34,15942.56,35053.44,18060.36,1636.21,5837.67,0.00,7052.54,2562.87,1573.66,163030.65,1302.02,0.00,57312.88,22259.44,91253.91,46.19,9.78,21.50,11.08,1.00,3.58,0.00,4.33,1.57,0.97,100,0.00,35.15,13.65,55.97
2017-01-01,66507.46,19339.91,32926.32,22435.80,3232.70,8661.72,0.00,8861.09,3035.82,1503.15,166503.97,1253.96,0.00,61630.64,28704.32,85847.37,39.94,11.62,19.78,13.47,1.94,5.20,0.00,5.32,1.82,0.90,100,0.00,37.01,17.24,51.56
2017-04-01,55241.60,2607.56,33183.89,18380.09,889.03,11303.02,0.00,7041.69,8249.76,1302.98,138199.62,898.18,0.00,60702.77,27518.88,57849.16,39.97,1.89,24.01,13.30,0.64,8.18,0.00,5.10,5.97,0.94,100,0.00,43.92,19.91,41.86
2017-07-01,51373.88,3816.70,33817.00,17537.18,1435.11,11654.01,0.00,6869.31,7119.65,1199.02,134821.86,921.82,0.00,59908.94,26091.94,55190.58,38.11,2.83,25.08,13.01,1.06,8.64,0.00,5.10,5.28,0.89,100,0.00,44.44,19.35,40.94
2017-10-01,65332.58,15460.25,31186.15,30083.98,2364.24,7360.87,4445.18,1719.73,2484.18,1478.51,161915.68,1133.09,4445.18,66118.55,34932.40,80792.84,40.35,9.55,19.26,18.58,1.46,4.55,2.75,1.06,1.53,0.91,100,2.75,40.84,21.57,49.90
2018-01-01,65321.43,16238.04,31085.78,30713.76,1709.35,11976.84,6061.40,343.00,3234.38,1440.40,168124.36,1109.99,6061.40,66743.27,35657.50,81559.47,38.85,9.66,18.49,18.27,1.02,7.12,3.61,0.20,1.92,0.86,100,3.61,39.70,21.21,48.51
2018-04-01,55996.43,1833.11,30966.65,18832.45,1120.01,11152.12,8041.48,448.34,8793.75,1241.04,138425.38,841.72,8041.48,59712.86,28746.21,57829.54,40.45,1.32,22.37,13.60,0.81,8.06,5.81,0.32,6.35,0.90,100,5.81,43.14,20.77,41.78
2018-07-01,50072.51,3444.26,32057.00,19454.55,1067.22,10940.68,8218.60,376.82,8005.83,995.24,134632.70,847.04,8218.60,60584.59,28527.60,53516.76,37.19,2.56,23.81,14.45,0.79,8.13,6.10,0.28,5.95,0.74,100,6.10,45.00,21.19,39.75
2018-10-01,59080.20,9282.88,27194.90,33485.97,2513.55,10004.25,9882.68,263.21,2716.44,1070.00,155494.08,965.57,9882.68,65910.85,38715.96,68363.08,38.00,5.97,17.49,21.54,1.62,6.43,6.36,0.17,1.75,0.69,100,6.36,42.39,24.90,43.97
2019-01-01,64357.49,5691.78,26149.05,32918.60,2229.75,14206.37,7964.23,266.67,3867.23,1076.80,158728.02,898.69,7964.23,65164.63,39015.58,70049.27,40.55,3.59,16.47,20.74,1.40,8.95,5.02,0.17,2.44,0.68,100,5.02,41.05,24.58,44.13
2019-04-01,56376.04,726.47,24582.71,22527.01,1046.30,12495.87,8334.41,239.32,8557.56,650.81,135536.46,830.70,8334.41,56713.57,32130.86,57102.50,41.59,0.54,18.14,16.62,0.77,9.22,6.15,0.18,6.31,0.48,100,6.15,41.84,23.71,42.13
2019-07-01,49420.60,822.52,25568.46,25979.95,1747.48,11225.60,8045.66,460.04,8130.42,705.97,132106.70,753.57,8045.66,61426.31,35857.85,50243.11,37.41,0.62,19.35,19.67,1.32,8.50,6.09,0.35,6.15,0.53,100,6.09,46.50,27.14,38.03
2019-10-01,58986.24,4633.06,29233.21,35446.89,2125.09,12318.48,10061.70,584.62,2422.55,942.97,156754.81,852.96,10061.70,69227.74,39994.53,63619.31,37.63,2.96,18.65,22.61,1.36,7.86,6.42,0.37,1.55,0.60,100,6.42,44.16,25.51,40.59
2020-01-01,46775.33,5903.80,24612.09,46391.86,3065.86,13487.42,9526.71,658.85,3892.23,820.43,155134.56,748.01,9526.71,77962.06,53349.96,52679.13,30.15,3.81,15.86,29.90,1.98,8.69,6.14,0.42,2.51,0.53,100,6.14,50.25,34.39,33.96
2020-04-01,37766.07,213.06,22460.10,25008.56,1392.19,11504.95,9292.22,677.12,10122.72,529.91,118966.90,662.83,9292.22,58983.57,36523.47,37979.14,31.75,0.18,18.88,21.02,1.17,9.67,7.81,0.57,8.51,0.45,100,7.81,49.58,30.70,31.92
2020-07-01,52244.60,532.14,20856.57,27324.12,1443.98,8334.65,7775.05,798.08,7739.17,611.69,127660.06,819.54,7775.05,57363.85,36507.27,52776.75,40.92,0.42,16.34,21.40,1.13,6.53,6.09,0.63,6.06,0.48,100,6.09,44.93,28.60,41.34
2020-10-01,53404.10,2116.55,26884.84,37877.49,2718.83,12743.33,9366.59,806.88,2331.71,1018.54,149268.86,755.06,9366.59,69812.86,42928.02,55520.65,35.78,1.42,18.01,25.38,1.82,8.54,6.27,0.54,1.56,0.68,100,6.27,46.77,28.76,37.20
2021-01-01,56854.07,4090.05,21706.04,38481.13,1987.68,14499.56,10325.52,909.77,3484.79,926.59,153265.19,806.21,10325.52,65659.63,43953.59,60944.12,37.10,2.67,14.16,25.11,1.30,9.46,6.74,0.59,2.27,0.60,100,6.74,42.84,28.68,39.76
2021-04-01,54013.68,1096.09,21587.88,22728.07,1298.46,14271.88,9256.35,843.80,9476.32,822.82,135395.35,793.19,9256.35,55090.74,33502.85,55109.77,39.89,0.81,15.94,16.79,0.96,10.54,6.84,0.62,7.00,0.61,100,6.84,40.69,24.74,40.70
2021-07-01,50675.92,2308.98,20203.59,20728.47,715.93,17193.79,8032.61,1031.50,7883.20,795.71,129569.70,865.33,8032.61,49531.19,29327.61,52984.90,39.11,1.78,15.59,16.00,0.55,13.27,6.20,0.80,6.08,0.61,100,6.20,38.23,22.63,40.89
2021-10-01,52986.52,2452.64,23336.30,42473.34,2472.37,12735.70,10420.74,879.74,2624.42,1064.50,151446.27,761.14,10420.74,70906.44,47570.12,55439.15,34.99,1.62,15.41,28.05,1.63,8.41,6.88,0.58,1.73,0.70,100,6.88,46.82,31.41,36.61
2022-01-01,49170.02,3756.85,23502.48,46348.88,2308.74,13676.91,9050.36,994.54,4340.68,1125.75,154275.23,723.94,9050.36,76500.80,52998.31,52926.87,31.87,2.44,15.23,30.04,1.50,8.87,5.87,0.64,2.81,0.73,100,5.87,49.59,34.35,34.31
2022-04-01,57492.90,668.63,24287.34,31701.14,1224.27,4937.98,6063.80,1202.55,9861.67,812.46,138252.75,796.75,6063.80,67074.41,42787.08,58161.53,41.59,0.48,17.57,22.93,0.89,3.57,4.39,0.87,7.13,0.59,100,4.39,48.52,30.95,42.07
2022-07-01,61279.57,2243.32,20374.96,26911.95,870.06,5204.06,8364.19,1534.56,9191.57,745.97,136720.19,937.59,8364.19,57348.54,36973.58,63522.88,44.82,1.64,14.90,19.68,0.64,3.81,6.12,1.12,6.72,0.55,100,6.12,41.95,27.04,46.46
2022-10-01,54515.51,1877.02,21290.92,49541.52,2254.23,8712.53,6461.87,1377.74,3082.02,1156.86,150270.24,734.66,6461.87,76168.70,54877.78,56392.53,36.28,1.25,14.17,32.97,1.50,5.80,4.30,0.92,2.05,0.77,100,4.30,50.69,36.52,37.53
2023-01-01,46898.91,1859.61,18446.04,47928.42,2146.33,18537.74,7169.62,1247.10,3775.52,1244.11,149253.43,662.17,7169.62,72296.31,53850.27,48758.52,31.42,1.25,12.36,32.11,1.44,12.42,4.80,0.84,2.53,0.83,100,4.80,48.44,36.08,32.67
2023-04-01,44208.96,182.33,19099.53,26651.81,781.55,18563.68,4751.02,1058.83,10928.46,519.34,126745.49,678.42,4751.02,57461.34,38361.80,44391.29,34.88,0.14,15.07,21.03,0.62,14.65,3.75,0.84,8.62,0.41,100,3.75,45.34,30.27,35.02
2023-07-01,41174.71,994.26,19768.44,32329.03,1229.43,14426.20,5622.40,1272.26,8909.27,430.10,126156.12,660.32,5622.40,62236.18,42467.75,42168.98,32.64,0.79,15.67,25.63,0.97,11.44,4.46,1.01,7.06,0.34,100,4.46,49.33,33.66,33.43
2023-10-01,40652.84,2490.55,19281.85,51058.15,2338.80,15328.84,9174.44,1558.15,3025.88,1121.70,146031.21,609.36,9174.44,75704.68,56422.83,43143.38,27.84,1.71,13.20,34.96,1.60,10.50,6.28,1.07,2.07,0.77,100,6.28,51.84,38.64,29.54

In [46]:
import plotly.graph_objs as go
import plotly.subplots as sp
import pandas as pd

# Example data: Extract data for 2009 and 2023
first_year = df_annual.iloc[0]
last_year = df_annual.iloc[-1]

# Define the energy categories
fossil_sources = ["GAS", "COAL", "NUCLEAR", "OTHER"]
renewable_sources = ["WIND", "HYDRO", "BIOMASS", "SOLAR"]

# Prepare data for the first year with "2009" at the center
labels_first = ["2009", "Fossil", "Renewable"] + fossil_sources + renewable_sources
parents_first = ["", "2009", "2009"] + ["Fossil"]*len(fossil_sources) + ["Renewable"]*len(renewable_sources)
values_first = [
    first_year[fossil_sources].sum() + first_year[renewable_sources].sum(),  # Total Energy
    first_year[fossil_sources].sum(),  # Fossil Total
    first_year[renewable_sources].sum(),  # Renewable Total
] + list(first_year[fossil_sources]) + list(first_year[renewable_sources])

# Prepare data for the last year with "2023" at the center
labels_last = ["2023", "Fossil", "Renewable"] + fossil_sources + renewable_sources
parents_last = ["", "2023", "2023"] + ["Fossil"]*len(fossil_sources) + ["Renewable"]*len(renewable_sources)
values_last = [
    last_year[fossil_sources].sum() + last_year[renewable_sources].sum(),  # Total Energy
    last_year[fossil_sources].sum(),  # Fossil Total
    last_year[renewable_sources].sum(),  # Renewable Total
] + list(last_year[fossil_sources]) + list(last_year[renewable_sources])

# Create the subplot layout
fig = sp.make_subplots(rows=1, cols=2, specs=[[{'type': 'sunburst'}, {'type': 'sunburst'}]])

# Add the first year sunburst to the first subplot
fig.add_trace(go.Sunburst(
    labels=labels_first,
    parents=parents_first,
    values=values_first,
    branchvalues="total",
    hoverinfo="label+percent entry",
), row=1, col=1)

# Add the last year sunburst to the second subplot
fig.add_trace(go.Sunburst(
    labels=labels_last,
    parents=parents_last,
    values=values_last,
    branchvalues="total",
    hoverinfo="label+percent entry",
), row=1, col=2)

# Update layout
fig.update_layout(
    title_text="Energy Distribution: 2009 vs 2023",
    paper_bgcolor='rgba(255, 255, 255, 1)',  # White background for better contrast
    margin=dict(t=50, l=25, r=25, b=25),
    sunburstcolorway=["#636EFA", "#EF553B", "#00CC96", "#AB63FA", "#FFA15A", "#19D3F3", "#FF6692", "#B6E880", "#FF97FF", "#FECB52"],
    uniformtext=dict(minsize=10, mode='hide')
)

fig.show()